# Generated by Django 5.1.15 on 2026-09-22 21:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["-created_at", "-id"], name="job_created_desc_idx"
                    ),
                    models.Index(fields=["name"], name="job_name_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_type",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "job statuses",
                "ordering": ("-timestamp", "-id"),
                "get_latest_by": ("timestamp", "id"),
                "indexes": [
                    models.Index(
                        fields=["job", "-timestamp", "-id"], name="jobstatus_latest_idx"
                    )
                ],
            },
        ),
    ]
