# Generated by Django 5.1.15 on 2026-09-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="job",
            name="job_name_idx",
        ),
        migrations.AddField(
            model_name="job",
            name="current_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                help_text="Newest entry in the job's status history. Maintained by record_status().",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["current_status", "-created_at", "-id"],
                name="job_status_created_idx",
            ),
        ),
    ]
